# Generated by Django 3.2.13 on 2022-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220601_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
