# Generated by Django 3.2.13 on 2022-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220602_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
