# Generated by Django 3.2.13 on 2022-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_aboutdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='related_abouts',
            field=models.IntegerField(default=0),
        ),
    ]
