# Generated by Django 3.2.13 on 2022-05-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='description',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
